### PR TITLE
Update LaravelToUML.php

### PR DESCRIPTION
**Pull request by xxaxxo**
Sometimes the second regex doesn't match either so a check would be nice

### CODE REVIEW

**Comment by andyabih** [comment]
What would be a possible syntax though that wouldn't match any of those, any idea?

**Comment by xxaxxo** [comment]
A defined relationship with new lines for the parameters - example:
return $this->hasManyThrough(
            Model::class,
            SomeOtherModel::class,
            'field_id',
            'id',
            'id',
            'other_field_id'
        );

- this results in Undefined offset: 1

**Comment by andyabih** [comment]
Ah that makes sense. I think a better approach would be handling that though, instead of ignoring it, since it's a relationship as well.

I'll look into addressing that specific scenario in the weekend, and of course feel free to submit a PR if you wanna tackle it.

Thanks for the heads up!

**Comment by xxaxxo** [comment]
I guess the getModelRelationships() can be rewritten to use $modelInstance->getRelations() method - so that it uses the native method for retrieving relations instead of preg_matching file_get_contents

**Comment by andyabih** [comment]
Not sure that would solve it I think, as you'll have to load the relations and then use getRelations(). But I'll look into it. Another approach could be to just call each method and check if it returns an instance of another model, but not sure how you'd be able to know the type of the relationship from that.

I will take a look at that scenario though, probably tomorrow and I'll have an update. Thanks again for pointing this out.

**Pull request closed without merging**
